"""Placeholder registry and default display values for fund summary reports."""

PLACEHOLDERS = {
    "FUND_NAME": "Full fund name",
    "TICKER": "Primary ticker symbol",
    "FUND_STANDARD_NAME": "Morningstar standard name",
    "INVESTMENT_TYPE": "e.g. Open-End Fund, ETF",
    "BASE_CURRENCY": "e.g. USD",
    "EXPENSE_RATIO": "Net expense ratio, e.g. 0.75%",
    "FEE_LEVEL": "Fee Level category (e.g. Low, Below Average)",
    "FEE_LEVEL_DISTRIBUTION": "Fee Level across distribution channels",
    "TWELVE_MONTH_YIELD": "Trailing 12-month yield",
    "TURNOVER_RATIO": "Portfolio turnover ratio",
    "SEC_YIELD": "SEC 30-day yield",
    "ACTIVE_INDEX_LABEL": "Active or Index",
    "FUND_SIZE": "Total net assets, formatted (e.g. $12.3B)",
    "CLOSED_TO_NEW": "Yes / No",
    "INCEPTION_DATE": "Share class inception date",
    "MIN_INITIAL_PURCHASE": "Minimum initial investment",
    "OLDEST_SHARE_CLASS_INCEPTION": "Oldest share class inception date",
    "NAV": "Net asset value (plain number, 2 decimals)",
    "EST_NET_FLOW_1M": "Estimated net flow 1 month (compact, e.g. -3.4B)",
    "EST_NET_FLOW_3M": "Estimated net flow 3 months (compact)",
    "EST_NET_FLOW_1Y": "Estimated net flow 1 year (compact)",
    "CATEGORY": "Morningstar Category",
    "PROSPECTUS_BENCHMARK": "Primary prospectus benchmark name",
    "MANAGER_INITIALS": "Lead PM initials (1-2 chars)",
    "MANAGER_NAME": "Lead portfolio manager full name",
    "MANAGER_START_DATE": "Manager start date on this fund",
    "MANAGER_OWNERSHIP": "Manager ownership range",
    "MEDALIST_RATING": "Gold / Silver / Bronze / Neutral / Negative",
    "MEDALIST_ANALYST_PCT": "Percent analyst-driven (0-100)",
    "MEDALIST_DISCLOSURE_TYPE": "CNAXS Medalist Rating disclosure type",
    "MEDALIST_DISCLOSURE_TYPE_DISPLAY": "Renderer-generated CNAXS display label",
    "MEDALIST_DISCLOSURE_FOOTNOTE": "Renderer-generated CNAXS disclosure footnote",
    "STAR_RATING": "Overall star rating integer (1-5)",
    "STAR_RATING_DISPLAY": "Star characters, e.g. ****",
    "STAR_RATING_ICON": "Inline SVG star-rating icon (auto-generated)",
    "MPRS": "Morningstar Portfolio Risk Score",
    "MPRS_VISUAL": "Inline SVG Morningstar Portfolio Risk Score dial (auto-generated)",
    "ALLOC_EQUITY_FUND": "Fund equity allocation %",
    "ALLOC_EQUITY_BENCH": "Benchmark equity allocation %",
    "ALLOC_BOND_FUND": "Fund fixed-income allocation %",
    "ALLOC_BOND_BENCH": "Benchmark fixed-income allocation %",
    "ALLOC_ALT_FUND": "Fund alternative allocation %",
    "ALLOC_ALT_BENCH": "Benchmark alternative allocation %",
    "ALLOC_CASH_FUND": "Fund cash allocation %",
    "ALLOC_CASH_BENCH": "Benchmark cash allocation %",
    "ALLOC_OTHER_FUND": "Fund other allocation %",
    "ALLOC_OTHER_BENCH": "Benchmark other allocation %",
    "TOP_HOLDINGS_ROWS": "HTML <tr> rows for top holdings table",
    "TOP_HOLDINGS": "Structured top holdings list: [{name, weight}, ...]",
    "NUM_HOLDINGS": "Total number of holdings",
    "PCT_TOP_10": "Percent of portfolio in top 10",
    "OWNERSHIP_BREADTH": "Ownership breadth descriptor",
    "LIQUIDITY_INTERMITTENT": "Intermittent liquidity %",
    "STYLE_BOX_EQUITY": "Equity style box label (e.g. Large Blend)",
    "STYLE_BOX_FIXED_INCOME": "Fixed-income style box label (e.g. Medium / Moderate)",
    "FI_DURATION": "Average effective duration (number or null)",
    "FI_CREDIT_QUALITY": "Average credit quality (e.g. A, BBB)",
    "FIXED_INCOME_REGION_ROWS": "List of dicts: [{label, fund, benchmark}, ...]",
    "REGIONAL_EXPOSURE_ROWS": "List of dicts: [{label, fund, benchmark}, ...]",
    "MARKET_CAP_ROWS": "List of dicts: [{label, fund, benchmark}, ...]",
    "EQUITY_PORTFOLIO_STATS_ROWS": "List of dicts: [{label, fund, benchmark, format}, ...]",
    "STYLE_BOX_SECTION_CLASS": "CSS class to hide/show style box section",
    "STYLE_BOX_ROWS": "HTML <tr> rows for style box table",
    "FIXED_INCOME_SECTION_CLASS": "CSS class to hide/show fixed-income section",
    "FIXED_INCOME_STATS_SECTION_CLASS": "CSS class to hide/show fixed-income stats subpanel",
    "FIXED_INCOME_REGION_SECTION_CLASS": "CSS class to hide/show fixed-income region subpanel",
    "FIXED_INCOME_REGION_HEADER": "HTML <tr> header for fixed-income region table",
    "FIXED_INCOME_REGION_ROWS_HTML": "HTML <tr> rows for fixed-income region table",
    "FIXED_INCOME_SECTION_NOTE": "HTML note for fixed-income section",
    "EQUITY_PROFILE_SECTION_CLASS": "CSS class to hide/show equity profile section",
    "REGIONAL_EXPOSURE_SECTION_CLASS": "CSS class to hide/show equity region section",
    "REGIONAL_EXPOSURE_HEADER": "HTML <tr> header for equity region table",
    "REGIONAL_EXPOSURE_ROWS_HTML": "HTML <tr> rows for equity region table",
    "REGIONAL_EXPOSURE_SECTION_NOTE": "HTML note for equity region section",
    "MARKET_CAP_SECTION_CLASS": "CSS class to hide/show market-cap section",
    "MARKET_CAP_HEADER": "HTML <tr> header for market-cap table",
    "MARKET_CAP_ROWS_HTML": "HTML <tr> rows for market-cap table",
    "MARKET_CAP_SECTION_NOTE": "HTML note for market-cap section",
    "EQUITY_PORTFOLIO_STATS_SECTION_CLASS": "CSS class to hide/show equity stats section",
    "EQUITY_PORTFOLIO_STATS_HEADER": "HTML <tr> header for equity stats table",
    "EQUITY_PORTFOLIO_STATS_ROWS_HTML": "HTML <tr> rows for equity stats table",
    "EQUITY_PORTFOLIO_STATS_SECTION_NOTE": "HTML note for equity stats section",
    "STYLE_BOX_SECTION": "Prebuilt HTML for style box section",
    "FIXED_INCOME_SECTION": "Prebuilt HTML for fixed-income section",
    "REGIONAL_EXPOSURE_SECTION": "Prebuilt HTML for regional exposure section",
    "MARKET_CAP_SECTION": "Prebuilt HTML for market-cap section",
    "EQUITY_PORTFOLIO_STATS_SECTION": "Prebuilt HTML for equity portfolio stats",
    "BENCHMARK_NAME": "Benchmark display name (chart legend)",
    "BENCHMARK_LEGEND_ENTRY": (
        "Full benchmark legend <span> HTML when currencies match; "
        "empty string when currencies differ"
    ),
    "BENCHMARK_CURRENCY_NOTE": (
        "HTML note shown when benchmark differs from fund currency "
        "(empty string when currencies match)"
    ),
    "TRAILING_RETURNS_ROWS": "HTML <tr> rows for trailing returns table",
    "TRAILING_RETURNS": "Structured trailing returns list: [{period, fund, benchmark}, ...]",
    "ANNUAL_RETURNS_HEADERS": "HTML <th> elements for each calendar year",
    "ANNUAL_RETURNS_ROWS": "HTML <tr> rows for annual returns table",
    "ANNUAL_RETURNS": "Structured annual returns list: [{year, fund, benchmark, rank}, ...]",
    "ANALYST_SUMMARY": "1-2 paragraph analyst narrative (HTML allowed)",
    "ANALYST_SUMMARY_PARAGRAPHS": "Structured analyst summary paragraphs as plain text",
    "PROCESS_RATING": "Process pillar rating word (may carry ^Q suffix)",
    "PROCESS_SCORE_TYPE": "Process pillar score type (Quantitative / Not returned)",
    "PROCESS_ICON": "Renderer-generated Process pillar score icon",
    "PROCESS_SUMMARY": "Process pillar 1-2 sentence summary",
    "PROCESS_SUMMARY_HTML": "Renderer-generated Process pillar summary HTML",
    "PEOPLE_RATING": "People pillar rating word (may carry ^Q suffix)",
    "PEOPLE_SCORE_TYPE": "People pillar score type (Quantitative / Not returned)",
    "PEOPLE_ICON": "Renderer-generated People pillar score icon",
    "PEOPLE_SUMMARY": "People pillar 1-2 sentence summary",
    "PEOPLE_SUMMARY_HTML": "Renderer-generated People pillar summary HTML",
    "PARENT_RATING": "Parent pillar rating word (may carry ^Q suffix if quant-driven)",
    "PARENT_SCORE_TYPE": "Parent pillar score type (Quantitative / Not returned)",
    "PARENT_ICON": "Renderer-generated Parent pillar score icon",
    "PARENT_SUMMARY": "Parent pillar 1-2 sentence summary",
    "PARENT_SUMMARY_HTML": "Renderer-generated Parent pillar summary HTML",
    "PRICE_RATING": "Price score value from MMRGS",
    "PROCESS_SCORE_SCALE": "Renderer-generated Process pillar score scale",
    "PEOPLE_SCORE_SCALE": "Renderer-generated People pillar score scale",
    "PARENT_SCORE_SCALE": "Renderer-generated Parent pillar score scale",
    "PRICE_SCORE": "Renderer-generated Price score display",
    "PRICE_SCORE_SCALE": "Renderer-generated Price score scale",
    "PRICE_SUMMARY": "Price pillar 1-2 sentence summary",
    "PRICE_SUMMARY_HTML": "Renderer-generated Price pillar summary HTML",
    "PILLAR_SUMMARIES": "Structured pillar summaries as plain text lists by pillar key",
    "REPORT_DATE": "Report generation date",
    "DATA_AS_OF_DATE": "Data as-of date",
    "CUMULATIVE_RETURNS_JSON": 'JSON array: [{"date":"2020-01-31","fund":10215,"benchmark":10180}, ...]',
    "CALENDAR_RETURNS_JSON": "Alias for CUMULATIVE_RETURNS_JSON (backward compat)",
    "ASSET_ALLOCATION_JSON": 'JSON array: [{"label":"Equity","value":65.2}, ...]',
    "RISK_DATA_JSON": (
        "JSON object with fund/benchmark keys for sharpe, upside, downside, "
        "stddev, alpha, beta, rsquared"
    ),
    "RETURNS_CHART_SVG": "Inline SVG line chart for returns (auto-generated)",
    "DONUT_CHART_SVG": "Inline SVG donut chart for allocation (auto-generated)",
}

_NUMERIC_FIELDS = {
    "EXPENSE_RATIO", "TWELVE_MONTH_YIELD", "TURNOVER_RATIO", "SEC_YIELD",
    "FUND_SIZE", "MIN_INITIAL_PURCHASE", "NAV", "EST_NET_FLOW_1M",
    "EST_NET_FLOW_3M", "EST_NET_FLOW_1Y", "NUM_HOLDINGS", "PCT_TOP_10",
    "OWNERSHIP_BREADTH", "LIQUIDITY_INTERMITTENT", "MPRS",
    "MEDALIST_ANALYST_PCT",
}
_TEXT_FIELDS = {
    "FUND_NAME", "TICKER", "FUND_STANDARD_NAME", "INVESTMENT_TYPE",
    "BASE_CURRENCY", "FEE_LEVEL", "FEE_LEVEL_DISTRIBUTION",
    "ACTIVE_INDEX_LABEL", "CLOSED_TO_NEW", "INCEPTION_DATE",
    "OLDEST_SHARE_CLASS_INCEPTION", "CATEGORY", "PROSPECTUS_BENCHMARK",
    "MANAGER_INITIALS", "MANAGER_NAME", "MANAGER_START_DATE",
    "MANAGER_OWNERSHIP", "MEDALIST_RATING", "MEDALIST_DISCLOSURE_TYPE", "STAR_RATING_DISPLAY",
    "BENCHMARK_NAME", "REPORT_DATE", "DATA_AS_OF_DATE",
    "PROCESS_SCORE_TYPE", "PEOPLE_SCORE_TYPE", "PARENT_SCORE_TYPE",
}
_HTML_FIELDS = {
    "TOP_HOLDINGS_ROWS", "TRAILING_RETURNS_ROWS", "ANNUAL_RETURNS_HEADERS",
    "ANNUAL_RETURNS_ROWS", "ANALYST_SUMMARY", "PROCESS_SUMMARY",
    "PROCESS_SUMMARY_HTML", "PEOPLE_SUMMARY", "PEOPLE_SUMMARY_HTML",
    "PARENT_SUMMARY", "PARENT_SUMMARY_HTML", "PRICE_SUMMARY", "PRICE_SUMMARY_HTML",
    "STYLE_BOX_SECTION", "FIXED_INCOME_SECTION", "REGIONAL_EXPOSURE_SECTION",
    "MARKET_CAP_SECTION", "EQUITY_PORTFOLIO_STATS_SECTION",
    "STYLE_BOX_SECTION_CLASS", "STYLE_BOX_ROWS",
    "FIXED_INCOME_SECTION_CLASS", "FIXED_INCOME_STATS_SECTION_CLASS", "FIXED_INCOME_REGION_SECTION_CLASS",
    "FIXED_INCOME_REGION_HEADER", "FIXED_INCOME_REGION_ROWS_HTML",
    "FIXED_INCOME_SECTION_NOTE", "EQUITY_PROFILE_SECTION_CLASS",
    "REGIONAL_EXPOSURE_SECTION_CLASS", "REGIONAL_EXPOSURE_HEADER",
    "REGIONAL_EXPOSURE_ROWS_HTML", "REGIONAL_EXPOSURE_SECTION_NOTE",
    "MARKET_CAP_SECTION_CLASS", "MARKET_CAP_HEADER", "MARKET_CAP_ROWS_HTML",
    "MARKET_CAP_SECTION_NOTE", "EQUITY_PORTFOLIO_STATS_SECTION_CLASS",
    "EQUITY_PORTFOLIO_STATS_HEADER", "EQUITY_PORTFOLIO_STATS_ROWS_HTML",
    "EQUITY_PORTFOLIO_STATS_SECTION_NOTE", "RETURNS_CHART_SVG", "DONUT_CHART_SVG",
    "STAR_RATING_ICON", "MPRS_VISUAL", "BENCHMARK_CURRENCY_NOTE", "BENCHMARK_LEGEND_ENTRY",
    "PROCESS_SCORE_SCALE", "PEOPLE_SCORE_SCALE", "PARENT_SCORE_SCALE", "PRICE_SCORE", "PRICE_SCORE_SCALE",
    "PROCESS_ICON", "PEOPLE_ICON", "PARENT_ICON", "MEDALIST_DISCLOSURE_TYPE_DISPLAY",
    "MEDALIST_DISCLOSURE_FOOTNOTE",
}
_JSON_FIELDS = {
    "CUMULATIVE_RETURNS_JSON", "CALENDAR_RETURNS_JSON",
    "ASSET_ALLOCATION_JSON", "RISK_DATA_JSON", "TOP_HOLDINGS",
    "TRAILING_RETURNS", "ANNUAL_RETURNS", "ANALYST_SUMMARY_PARAGRAPHS",
    "PILLAR_SUMMARIES",
}

_JSON_OBJECT_FIELDS = {"RISK_DATA_JSON", "PILLAR_SUMMARIES"}


def default_for(key: str) -> str:
    """Return the appropriate display default for a missing placeholder."""
    if key in _HTML_FIELDS:
        return ""
    if key in _JSON_OBJECT_FIELDS:
        return "{}"
    if key in _JSON_FIELDS:
        return "[]"
    if key in _NUMERIC_FIELDS:
        return "--"
    if key in _TEXT_FIELDS:
        return "N/A"
    return "--"
