// TeacherAI.pptx — recreated with pptxgenjs
// Usage:
//   npm install pptxgenjs
//   node TeacherAI.js
// Produces: TeacherAI.pptx
const PptxGenJS = require('pptxgenjs');

const pptx = new PptxGenJS();
// The original deck uses a custom 20" x 11.25" page (16:9)
pptx.defineLayout({ name: 'TEACHERAI_WIDE', width: 20, height: 11.25 });
pptx.layout = 'TEACHERAI_WIDE';

// ===== Slide 1 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.0417, "y": 1.0938, "w": 0.2292, "h": 0.2292, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "TeacherAI", "options": {"fontSize": 21.0, "color": "0F1E17", "fontFace": "Arial", "align": "left"}}], {"x": 1.4167, "y": 1.0417, "w": 1.4253, "h": 0.375, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "DISTRICT OVERVIEW · 2026", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 14.7783, "y": 1.0417, "w": 4.3054, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "The classroom, ", "options": {"fontSize": 165.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -4.95, "align": "left", "lineSpacingMultiple": 0.92}}, {"text": "remembered.", "options": {"fontSize": 165.0, "bold": true, "italic": true, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -4.95, "align": "left", "lineSpacingMultiple": 0.92}}], {"x": 1.0417, "y": 2.2759, "w": 18.4542, "h": 4.2686, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "An AI companion that records every lesson, turns it into on-demand video for students, and generates aligned quizzes and tests — automatically.", "options": {"fontSize": 25.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 1.0417, "y": 6.9194, "w": 11.8021, "h": 1.4757, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "AUDIENCE ", "options": {"fontSize": 13.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}, {"text": "DISTRICT ADMINISTRATORS", "options": {"fontSize": 13.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}], {"x": 1.0417, "y": 9.6084, "w": 3.1597, "h": 0.6416, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "GRADE SPAN ", "options": {"fontSize": 13.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}, {"text": "K–12 & HIGHER ED", "options": {"fontSize": 13.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}], {"x": 4.7344, "y": 9.6084, "w": 2.1107, "h": 0.6416, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "FORMAT ", "options": {"fontSize": 13.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}, {"text": "5-MINUTE OVERVIEW", "options": {"fontSize": 13.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.35, "align": "left", "lineSpacingMultiple": 1.6}}], {"x": 7.3867, "y": 9.6084, "w": 2.3836, "h": 0.6416, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "CONFIDENTIAL", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 16.8683, "y": 9.9167, "w": 2.1733, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 2 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "01 · THE PROBLEM", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "The teacher's impossible week.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Every week, the same three jobs compete for the same finite hours — and the ones students need most get the least time.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.6841, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 4.6216, "w": 4.2292, "h": 5.7951, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "54", "options": {"fontSize": 97.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}, {"text": "hr", "options": {"fontSize": 33.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}], {"x": 1.4688, "y": 5.0903, "w": 3.4762, "h": 1.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Average weekly hours worked by U.S. K-12 teachers, far beyond contracted time.", "options": {"fontSize": 19.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 1.4688, "y": 7.944, "w": 3.4762, "h": 1.5039, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "REF · TEACHER WORKLOAD STUDIES", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 1.4688, "y": 9.5729, "w": 3.4762, "h": 0.4167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 5.6042, "y": 4.6216, "w": 4.2292, "h": 5.7951, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "7", "options": {"fontSize": 97.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}, {"text": "hr", "options": {"fontSize": 33.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}], {"x": 6.0312, "y": 5.0903, "w": 3.4762, "h": 1.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Hours each week spent creating assessments, quizzes, and answer keys.", "options": {"fontSize": 19.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 6.0312, "y": 8.4971, "w": 3.4762, "h": 1.1383, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "REF · INTERNAL SURVEY, N=220", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 6.0312, "y": 9.7604, "w": 3.4762, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 10.1667, "y": 4.6216, "w": 4.2292, "h": 5.7951, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "1 ", "options": {"fontSize": 97.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}, {"text": "in", "options": {"fontSize": 33.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}, {"text": "5", "options": {"fontSize": 97.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}], {"x": 10.5938, "y": 5.0903, "w": 3.4762, "h": 1.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Students absent at least once a week, missing instruction that's rarely recovered.", "options": {"fontSize": 19.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 10.5938, "y": 8.1315, "w": 3.4762, "h": 1.5039, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "REF · CHRONIC ABSENTEEISM DATA", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 10.5938, "y": 9.7604, "w": 3.4762, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 14.7292, "y": 4.6216, "w": 4.2292, "h": 5.7951, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "0", "options": {"fontSize": 97.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -2.92, "align": "left", "lineSpacingMultiple": 0.9}}], {"x": 15.1562, "y": 5.0903, "w": 3.4762, "h": 1.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Durable record of what was actually taught in the room — lessons vanish the moment they end.", "options": {"fontSize": 19.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 15.1562, "y": 8.1315, "w": 3.4762, "h": 1.5039, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "REF · STATUS QUO", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 15.1562, "y": 9.7604, "w": 3.4762, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "02 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 3 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "02 · THE SYSTEM", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "How TeacherAI fits the classroom.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "One quiet device in the room captures the lesson. Everything after is automatic — and reviewable by the teacher before it ever reaches a student.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.6841, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 4.5382, "w": 5.4167, "h": 5.8784, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "STEP 01", "options": {"fontSize": 13.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.62, "align": "left"}}], {"x": 1.4271, "y": 4.9653, "w": 4.7852, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Record the lesson", "options": {"fontSize": 39.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.4271, "y": 5.3924, "w": 4.7852, "h": 0.5941, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Teacher taps once. Audio, board work, and slides are captured alongside a live transcript.", "options": {"fontSize": 18.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 1.4271, "y": 6.1532, "w": 4.7852, "h": 1.1291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.2917, "y": 4.5382, "w": 5.4167, "h": 5.8784, "fill": {"color": "1E5A3F"}, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "STEP 02", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 1.62, "align": "left"}}], {"x": 7.6771, "y": 4.9653, "w": 4.7852, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "AI processes & aligns", "options": {"fontSize": 39.0, "color": "F4F1EA", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 7.6771, "y": 5.3924, "w": 4.7852, "h": 1.1465, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Lesson is chaptered, indexed to standards, and cross-referenced with uploaded class materials.", "options": {"fontSize": 18.0, "color": "F4F1EA", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 7.6771, "y": 6.7056, "w": 4.7852, "h": 1.1291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.5417, "y": 4.5382, "w": 5.4167, "h": 5.8784, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "STEP 03", "options": {"fontSize": 13.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.62, "align": "left"}}], {"x": 13.9271, "y": 4.9653, "w": 4.7852, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Students learn & practice", "options": {"fontSize": 39.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 13.9271, "y": 5.3924, "w": 4.7852, "h": 1.1465, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Chaptered playback, searchable transcripts, and auto-generated quizzes land in each student's account.", "options": {"fontSize": 18.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 13.9271, "y": 6.7056, "w": 4.7852, "h": 1.1291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "03 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 4 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "03 · CAPTURE", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "One tap to record the ", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}, {"text": "lesson.", "options": {"fontSize": 63.0, "bold": true, "italic": true, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Designed to disappear into the classroom. No microphones to clip on, no cameras to aim, no software to configure mid-period.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.6841, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.0417, "y": 4.9451, "w": 0.5208, "h": 0.5208, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "01", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "align": "center"}}], {"x": 1.0104, "y": 4.9556, "w": 0.5833, "h": 0.5417, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Dedicated room device", "options": {"fontSize": 24.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 1.9583, "y": 4.9451, "w": 7.6821, "h": 0.4082, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "A wall-mounted or desktop unit with far-field mics picks up the teacher and student questions clearly from across the room.", "options": {"fontSize": 15.75, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.9583, "y": 5.3742, "w": 7.6821, "h": 0.654, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.0417, "y": 6.2365, "w": 0.5208, "h": 0.5208, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "02", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "align": "center"}}], {"x": 1.0104, "y": 6.2469, "w": 0.5833, "h": 0.5417, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Smart chaptering, live", "options": {"fontSize": 24.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 1.9583, "y": 6.2365, "w": 7.6821, "h": 0.4082, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Topic shifts are detected in real time, producing named chapters like \"Mitosis intro\" or \"Homework review\" without any tagging by the teacher.", "options": {"fontSize": 15.75, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.9583, "y": 6.6655, "w": 7.6821, "h": 0.654, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.0417, "y": 7.5278, "w": 0.5208, "h": 0.5208, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "03", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "align": "center"}}], {"x": 1.0104, "y": 7.5382, "w": 0.5833, "h": 0.5417, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Privacy by default", "options": {"fontSize": 24.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 1.9583, "y": 7.5278, "w": 7.6821, "h": 0.4082, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Student voices can be suppressed or anonymized. Recordings are encrypted, district-owned, and never used to train external models.", "options": {"fontSize": 15.75, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.9583, "y": 7.9569, "w": 7.6821, "h": 0.654, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.0417, "y": 8.8192, "w": 0.5208, "h": 0.5208, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "04", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "align": "center"}}], {"x": 1.0104, "y": 8.8296, "w": 0.5833, "h": 0.5417, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Teacher always in control", "options": {"fontSize": 24.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 1.9583, "y": 8.8192, "w": 7.6821, "h": 0.4082, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Pause, redact, or discard any portion before publishing. Nothing reaches students until the teacher releases it.", "options": {"fontSize": 15.75, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.9583, "y": 9.2482, "w": 7.6821, "h": 0.654, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 10.3333, "y": 4.3716, "w": 8.625, "h": 6.0625, "fill": {"color": "0F1E17"}, "line": {"color": "1F3028", "width": 0.75}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 10.5521, "y": 4.5903, "w": 8.1875, "h": 5.625, "fill": {"color": "F4F1EA"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.rect, {"x": 10.5521, "y": 5.132, "w": 8.1875, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "ROOM 214 · BIOLOGY", "options": {"fontSize": 10.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.84, "align": "left"}}], {"x": 10.8021, "y": 4.7778, "w": 1.8312, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "RECORDING", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.84, "align": "left"}}], {"x": 17.2707, "y": 4.7778, "w": 1.3022, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Period 3 — Cell Division", "options": {"fontSize": 28.5, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 10.8438, "y": 5.4237, "w": 4.4226, "h": 0.4792, "shape": pptx.ShapeType.rect, "margin": 0.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Tuesday, April 21 · 10:42 AM", "options": {"fontSize": 13.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.27, "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 10.8438, "y": 5.932, "w": 7.8323, "h": 0.2479, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "00:18:42", "options": {"fontSize": 43.5, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -0.87, "align": "left"}}], {"x": 10.8438, "y": 6.3465, "w": 7.8323, "h": 0.7396, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 10.8438, "y": 7.4277, "w": 0.2769, "h": 0.1499, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.1623, "y": 7.3652, "w": 0.277, "h": 0.2749, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.481, "y": 7.3078, "w": 0.2769, "h": 0.39, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.7995, "y": 7.3978, "w": 0.277, "h": 0.21, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 12.1182, "y": 7.2827, "w": 0.2769, "h": 0.4399, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 12.4367, "y": 7.3428, "w": 0.277, "h": 0.32, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 12.7554, "y": 7.4152, "w": 0.2769, "h": 0.175, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 13.0739, "y": 7.3228, "w": 0.277, "h": 0.3599, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 13.3926, "y": 7.3577, "w": 0.2769, "h": 0.2899, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 13.7111, "y": 7.2977, "w": 0.277, "h": 0.41, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.0298, "y": 7.3877, "w": 0.2769, "h": 0.23, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.3483, "y": 7.3328, "w": 0.277, "h": 0.3398, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.667, "y": 7.2778, "w": 0.2769, "h": 0.4499, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.9855, "y": 7.3727, "w": 0.277, "h": 0.2599, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 15.3042, "y": 7.4077, "w": 0.2769, "h": 0.1899, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 15.6227, "y": 7.3177, "w": 0.277, "h": 0.37, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 15.9414, "y": 7.3527, "w": 0.2769, "h": 0.3, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 16.2599, "y": 7.3828, "w": 0.2769, "h": 0.2399, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 16.5785, "y": 7.3027, "w": 0.2769, "h": 0.3999, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 16.897, "y": 7.3628, "w": 0.2769, "h": 0.2799, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 17.2155, "y": 7.3377, "w": 0.2769, "h": 0.3299, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 17.534, "y": 7.3978, "w": 0.2769, "h": 0.21, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 17.8525, "y": 7.3278, "w": 0.2769, "h": 0.3499, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 18.1711, "y": 7.4128, "w": 0.2769, "h": 0.1799, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 10.8438, "y": 7.9611, "w": 2.0312, "h": 0.3646, "fill": {"color": "D6E5DC"}, "line": {"type": "none"}});
  s.addText([{"text": "▸ Chapter 1 · Review", "options": {"fontSize": 12.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.48, "align": "left"}}], {"x": 11.0104, "y": 8.0444, "w": 1.7812, "h": 0.2396, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 12.9792, "y": 7.9611, "w": 2.0099, "h": 0.3646, "fill": {"color": "D6E5DC"}, "line": {"type": "none"}});
  s.addText([{"text": "▸ Chapter 2 · Mitosis", "options": {"fontSize": 12.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.48, "align": "left"}}], {"x": 13.1458, "y": 8.0444, "w": 1.7599, "h": 0.2396, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 15.0933, "y": 7.9611, "w": 1.7581, "h": 0.3646, "fill": {"color": "E8E2D1"}, "line": {"type": "none"}});
  s.addText([{"text": "Now chaptering…", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.48, "align": "left"}}], {"x": 15.2599, "y": 8.0444, "w": 1.5081, "h": 0.2396, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 10.8438, "y": 9.0174, "w": 7.6042, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Auto-upload on stop", "options": {"fontSize": 12.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.48, "align": "left"}}], {"x": 10.8438, "y": 9.507, "w": 1.7074, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 16.2738, "y": 9.2778, "w": 2.1742, "h": 0.6458, "fill": {"color": "D13A2B"}, "line": {"type": "none"}});
  s.addText([{"text": "■ End lesson", "options": {"fontSize": 15.0, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 0.6, "align": "left"}}], {"x": 16.6904, "y": 9.4653, "w": 1.4242, "h": 0.3125, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "04 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 5 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "04 · STUDENTS", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Student playback, anywhere.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Absent, confused, or reviewing for an exam — students return to the exact moment they need, with a transcript they can search.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.6841, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.0417, "y": 4.769, "w": 3.5833, "h": 5.25, "fill": {"color": "0F1E17"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.1667, "y": 4.894, "w": 3.3333, "h": 5.0, "fill": {"color": "F4F1EA"}, "line": {"type": "none"}});
  s.addText([{"text": "9:41", "options": {"fontSize": 9.75, "color": "0F1E17", "fontFace": "Arial", "align": "left"}}], {"x": 1.4583, "y": 5.0607, "w": 0.347, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "●●●", "options": {"fontSize": 9.75, "color": "0F1E17", "fontFace": "Arial", "align": "left"}}], {"x": 3.9629, "y": 5.0607, "w": 0.3288, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "BIOLOGY · APR 21", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.16, "align": "left"}}], {"x": 1.3958, "y": 5.3836, "w": 2.9613, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Cell Division & Mitosis", "options": {"fontSize": 19.5, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.1}}], {"x": 1.3958, "y": 5.5503, "w": 2.9613, "h": 0.3395, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.3333, "y": 5.9731, "w": 3.0, "h": 1.875, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.ellipse, {"x": 2.5208, "y": 6.5981, "w": 0.625, "h": 0.625, "fill": {"color": "F4F1EA"}, "line": {"type": "none"}});
  s.addText([{"text": "18:42", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 1.4167, "y": 7.994, "w": 0.3701, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.8076, "y": 8.0356, "w": 2.0514, "h": 0.0417, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "44:10", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 3.9632, "y": 7.994, "w": 0.3701, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "CHAPTERS", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.16, "align": "left"}}], {"x": 1.375, "y": 8.2856, "w": 3.0042, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "00:00", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 1.5, "y": 8.6229, "w": 0.625, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Warm-up & review", "options": {"fontSize": 11.25, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.25}}], {"x": 2.1458, "y": 8.5981, "w": 1.8408, "h": 0.237, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "5m", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 4.0075, "y": 8.6333, "w": 0.2425, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.375, "y": 8.981, "w": 2.9167, "h": 0.4036, "fill": {"color": "D6E5DC"}, "line": {"type": "none"}});
  s.addText([{"text": "05:20", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "align": "left"}}], {"x": 1.5, "y": 9.1099, "w": 0.625, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Phases of mitosis", "options": {"fontSize": 11.25, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.25}}], {"x": 2.1458, "y": 9.0851, "w": 1.777, "h": 0.237, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "13m", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 3.9437, "y": 9.1203, "w": 0.3063, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "18:40", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 1.5, "y": 9.6945, "w": 0.625, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Worked example: onion root", "options": {"fontSize": 11.25, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.25}}], {"x": 2.1458, "y": 9.5721, "w": 1.7855, "h": 0.4323, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "11m", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "align": "left"}}], {"x": 3.9521, "y": 9.7049, "w": 0.2979, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 5.5417, "y": 4.6344, "w": 13.4167, "h": 1.7008, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Chaptered video + transcript", "options": {"fontSize": 25.5, "bold": true, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 5.8854, "y": 4.9365, "w": 13.111, "h": 0.4134, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "AI generates named chapters so students jump straight to \"Worked example\" instead of scrubbing. Every word is searchable — type \"prophase\" and land on the moment it was taught.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.8854, "y": 5.3916, "w": 13.111, "h": 0.6833, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 5.5417, "y": 6.5436, "w": 13.4167, "h": 1.7008, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Ask the lesson a question", "options": {"fontSize": 25.5, "bold": true, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 5.8854, "y": 6.8457, "w": 13.111, "h": 0.4134, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Students can ask \"Can you explain that again, simpler?\" and get an answer grounded in what their teacher actually said, in their teacher's own words — not a generic chatbot response.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.8854, "y": 7.3008, "w": 13.111, "h": 0.6833, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 5.5417, "y": 8.4528, "w": 13.4167, "h": 1.7008, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Accessible by default", "options": {"fontSize": 25.5, "bold": true, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 5.8854, "y": 8.7549, "w": 13.111, "h": 0.4134, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Live captions, translated transcripts in 40+ languages, adjustable playback speed, and screen-reader support — included, not add-ons.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.8854, "y": 9.21, "w": 13.111, "h": 0.6833, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "05 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 6 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "05 · ASSESSMENT", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Quizzes aligned to the ", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}, {"text": "lesson.", "options": {"fontSize": 63.0, "bold": true, "italic": true, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 17.1667, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Questions come from what was actually taught — not a generic question bank. The teacher reviews, edits, and approves in minutes.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.7257, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 4.4966, "w": 5.6943, "h": 5.9201, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "SOURCE", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.13, "align": "left"}}], {"x": 1.3438, "y": 4.7987, "w": 0.8457, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "From the lesson & materials", "options": {"fontSize": 22.5, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 1.3438, "y": 5.1216, "w": 5.2429, "h": 0.3698, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "10:42 · Lesson transcript", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 1.3438, "y": 5.5955, "w": 5.2429, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.3438, "y": 5.783, "w": 0.0208, "h": 0.4688, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "\"…so ", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "prophase ", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "is when the chromosomes first ", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "condense and become visible ", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": ", and the nuclear envelope starts to break down…\"", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 1.4896, "y": 5.783, "w": 5.097, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Uploaded · Chapter 10 notes", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 1.3438, "y": 6.3976, "w": 5.2429, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.3438, "y": 6.5851, "w": 0.0208, "h": 0.4688, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Mitosis proceeds through four phases: ", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "prophase, metaphase, anaphase, telophase ", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": ".", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 1.4896, "y": 6.5851, "w": 5.097, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "23:15 · Whiteboard capture", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.72, "align": "left"}}], {"x": 1.3438, "y": 7.1997, "w": 5.2429, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.3438, "y": 7.3872, "w": 0.0208, "h": 0.4688, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Diagram: spindle fibers attaching to centromeres during ", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "metaphase ", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}, {"text": "alignment.", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 1.4896, "y": 7.3872, "w": 5.097, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.1527, "y": 4.4966, "w": 5.6945, "h": 5.9201, "fill": {"color": "D6E5DC"}, "line": {"color": "1E5A3F", "width": 0.75}});
  s.addText([{"text": "GENERATED", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.13, "align": "left"}}], {"x": 7.4548, "y": 4.7987, "w": 1.1847, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Aligned questions, mixed formats", "options": {"fontSize": 22.5, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 7.4548, "y": 5.1216, "w": 5.243, "h": 0.3698, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.4548, "y": 5.5955, "w": 5.0903, "h": 1.7936, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "MULTIPLE CHOICE · RECALL", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 7.6735, "y": 5.7726, "w": 4.7924, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "During which phase of mitosis do chromosomes first become visible?", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 7.6735, "y": 6.0018, "w": 4.7924, "h": 0.4915, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Prophase", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "-apple-system", "align": "left"}}], {"x": 7.6735, "y": 6.5558, "w": 4.7924, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Metaphase", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 7.6735, "y": 6.7954, "w": 4.7924, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addText([{"text": "Anaphase", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 7.6735, "y": 7.035, "w": 4.7924, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "middle", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.4548, "y": 7.535, "w": 5.0903, "h": 1.1374, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "SHORT ANSWER · APPLY", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 7.6735, "y": 7.7121, "w": 4.7924, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Explain, in your own words, what happens to spindle fibers during metaphase.", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 7.6735, "y": 7.9412, "w": 4.7924, "h": 0.4915, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.4548, "y": 8.8182, "w": 5.0903, "h": 0.9124, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "ORDERING · SEQUENCE", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 7.6735, "y": 8.9953, "w": 4.7924, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Place the four phases of mitosis in the correct order.", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.35}}], {"x": 7.6735, "y": 9.2244, "w": 4.7924, "h": 0.2666, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.2638, "y": 4.4966, "w": 5.6945, "h": 5.9201, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "DELIVERED", "options": {"fontSize": 11.25, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.13, "align": "left"}}], {"x": 13.5659, "y": 4.7987, "w": 1.125, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Teacher-reviewed, then shipped", "options": {"fontSize": 22.5, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 13.5659, "y": 5.1216, "w": 5.243, "h": 0.3698, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.5659, "y": 5.5955, "w": 0.0208, "h": 0.4688, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "Teacher reviews 12 generated items, removes 2, rewords 1, and sets difficulty — typically in under 4 minutes.", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 13.7118, "y": 5.5955, "w": 5.0972, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.5659, "y": 6.2101, "w": 0.0208, "h": 0.4688, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "System builds parallel versions for retakes and differentiated groups (IEP, ELL, enrichment).", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 13.7118, "y": 6.2101, "w": 5.0972, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.5659, "y": 6.8247, "w": 0.0208, "h": 0.4688, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "Auto-graded where possible; short-answer responses come back with rubric-based suggested scores.", "options": {"fontSize": 11.25, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 13.7118, "y": 6.8247, "w": 5.0972, "h": 0.5104, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.5659, "y": 9.8125, "w": 2.0483, "h": 0.3021, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Export · Google Classroom", "options": {"fontSize": 9.75, "color": "2A3D33", "fontFace": "Arial", "charSpacing": 0.39, "align": "left"}}], {"x": 13.7013, "y": 9.8854, "w": 1.8608, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 15.6976, "y": 9.8125, "w": 1.1003, "h": 0.3021, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Canvas LMS", "options": {"fontSize": 9.75, "color": "2A3D33", "fontFace": "Arial", "charSpacing": 0.39, "align": "left"}}], {"x": 15.833, "y": 9.8854, "w": 0.9128, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 16.8812, "y": 9.8125, "w": 0.9565, "h": 0.3021, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "Schoology", "options": {"fontSize": 9.75, "color": "2A3D33", "fontFace": "Arial", "charSpacing": 0.39, "align": "left"}}], {"x": 17.0166, "y": 9.8854, "w": 0.769, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 17.9211, "y": 9.8125, "w": 0.5579, "h": 0.3021, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "PDF", "options": {"fontSize": 9.75, "color": "2A3D33", "fontFace": "Arial", "charSpacing": 0.39, "align": "left"}}], {"x": 18.0565, "y": 9.8854, "w": 0.3704, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "06 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 7 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "06 · TEACHER DASHBOARD", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "The teacher dashboard.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Every lesson, video, quiz, and class result in one place — with the teacher's edits always a click away.", "options": {"fontSize": 22.5, "color": "5C6B63", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 1.0417, "y": 2.6841, "w": 12.875, "h": 0.9167, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 4.3716, "w": 17.9167, "h": 6.0451, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0521, "y": 4.382, "w": 2.7083, "h": 6.0243, "fill": {"color": "0F1E17"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.ellipse, {"x": 1.3021, "y": 4.8091, "w": 0.1458, "h": 0.1458, "fill": {"color": "2A7A56"}, "line": {"type": "none"}});
  s.addText([{"text": "TeacherAI", "options": {"fontSize": 21.0, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.5729, "y": 4.7153, "w": 1.4253, "h": 0.375, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 1.3021, "y": 5.4237, "w": 2.2083, "h": 0.4688, "fill": {"color": "FFFFFF"}, "line": {"type": "none"}});
  s.addText([{"text": "Lessons", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 5.5487, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Assessments", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 6.1007, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Classes", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 6.6528, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Students", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 7.2049, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Standards", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 7.757, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Settings", "options": {"fontSize": 13.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 1.4479, "y": 8.3091, "w": 2.0, "h": 0.2604, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "MS. ALVAREZ WESTBROOK HS · BIOLOGY", "options": {"fontSize": 9.0, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 1.3021, "y": 9.7812, "w": 2.2917, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "This week", "options": {"fontSize": 27.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "align": "left"}}], {"x": 4.1771, "y": 4.757, "w": 1.7715, "h": 0.4792, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "APR 20 – APR 24", "options": {"fontSize": 10.5, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.84, "align": "left"}}], {"x": 17.1969, "y": 4.9653, "w": 1.4176, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1771, "y": 5.4445, "w": 3.4635, "h": 1.0625, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "LESSONS CAPTURED", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.99, "align": "left"}}], {"x": 4.3958, "y": 5.6424, "w": 3.1168, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "12", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.0}}], {"x": 4.3958, "y": 5.8507, "w": 3.1168, "h": 0.5, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.8073, "y": 5.4445, "w": 3.4635, "h": 1.0625, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "STUDENT VIEWS", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.99, "align": "left"}}], {"x": 8.026, "y": 5.6424, "w": 3.1168, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "847", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.0}}], {"x": 8.026, "y": 5.8507, "w": 3.1168, "h": 0.5, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 11.4375, "y": 5.4445, "w": 3.4635, "h": 1.0625, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "QUIZZES DEPLOYED", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.99, "align": "left"}}], {"x": 11.6562, "y": 5.6424, "w": 3.1168, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "8", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.0}}], {"x": 11.6562, "y": 5.8507, "w": 3.1168, "h": 0.5, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 15.0677, "y": 5.4445, "w": 3.4635, "h": 1.0625, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "PREP TIME SAVED", "options": {"fontSize": 8.25, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.99, "align": "left"}}], {"x": 15.2865, "y": 5.6424, "w": 3.1168, "h": 0.1667, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "6.4 ", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.0}}, {"text": "hrs", "options": {"fontSize": 15.0, "color": "1E5A3F", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.0}}], {"x": 15.2865, "y": 5.8507, "w": 3.1168, "h": 0.5, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1771, "y": 6.757, "w": 14.3542, "h": 3.2743, "fill": {"color": "F4F1EA"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1875, "y": 7.2466, "w": 14.3333, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "LESSON", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 4.4167, "y": 6.9341, "w": 4.5347, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "CLASS", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 8.986, "y": 6.9341, "w": 2.7251, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "QUIZ STATUS", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 11.7944, "y": 6.9341, "w": 2.2847, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "CLASS AVG", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 14.1624, "y": 6.9341, "w": 2.2847, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "VIEWS", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.9, "align": "left"}}], {"x": 16.5304, "y": 6.9341, "w": 1.8444, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1875, "y": 7.9132, "w": 14.3333, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Cell Division & Mitosis", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 7.4028, "w": 1.7336, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 0.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Apr 21 · 44 min", "options": {"fontSize": 9.75, "color": "5C6B63", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 7.6112, "w": 4.5347, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Bio 1 · P3", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 8.986, "y": 7.4914, "w": 2.7251, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.7944, "y": 7.4705, "w": 0.9967, "h": 0.2292, "fill": {"color": "D6E5DC"}, "line": {"type": "none"}});
  s.addText([{"text": "PUBLISHED", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.54, "align": "left"}}], {"x": 11.8986, "y": 7.5122, "w": 0.8717, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 7.5539, "w": 2.2013, "h": 0.0625, "fill": {"color": "ECE7DC"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 7.5539, "w": 1.805, "h": 0.0625, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "124", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 16.5304, "y": 7.4914, "w": 1.8444, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1875, "y": 8.5799, "w": 14.3333, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Photosynthesis Review", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 8.0695, "w": 1.8065, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 0.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Apr 20 · 38 min", "options": {"fontSize": 9.75, "color": "5C6B63", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 8.2778, "w": 4.5347, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Bio 1 · P3", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 8.986, "y": 8.158, "w": 2.7251, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.7944, "y": 8.1372, "w": 0.9967, "h": 0.2292, "fill": {"color": "D6E5DC"}, "line": {"type": "none"}});
  s.addText([{"text": "PUBLISHED", "options": {"fontSize": 9.0, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 0.54, "align": "left"}}], {"x": 11.8986, "y": 8.1789, "w": 0.8717, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 8.2205, "w": 2.2013, "h": 0.0625, "fill": {"color": "ECE7DC"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 8.2205, "w": 1.673, "h": 0.0625, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "98", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 16.5304, "y": 8.158, "w": 1.8444, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 4.1875, "y": 9.2466, "w": 14.3333, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "Meiosis Intro", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 8.7362, "w": 1.0444, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 0.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Apr 22 · 41 min", "options": {"fontSize": 9.75, "color": "5C6B63", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 8.9445, "w": 4.5347, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Bio 1 · P5", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 8.986, "y": 8.8247, "w": 2.7251, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.7944, "y": 8.8039, "w": 1.2692, "h": 0.2292, "fill": {"color": "F2E6D2"}, "line": {"type": "none"}});
  s.addText([{"text": "NEEDS REVIEW", "options": {"fontSize": 9.0, "color": "B8874A", "fontFace": "Arial", "charSpacing": 0.54, "align": "left"}}], {"x": 11.8986, "y": 8.8455, "w": 1.1442, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 8.8872, "w": 2.2013, "h": 0.0625, "fill": {"color": "ECE7DC"}, "line": {"type": "none"}});
  s.addText([{"text": "—", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 16.5304, "y": 8.8247, "w": 1.8444, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Genetic Variation Lab", "options": {"fontSize": 12.0, "color": "0F1E17", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 9.4028, "w": 1.6738, "h": 0.2188, "shape": pptx.ShapeType.rect, "margin": 0.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Apr 23 · 52 min", "options": {"fontSize": 9.75, "color": "5C6B63", "fontFace": "-apple-system", "align": "left"}}], {"x": 4.4167, "y": 9.6112, "w": 4.5347, "h": 0.1979, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Bio Honors", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 8.986, "y": 9.4914, "w": 2.7251, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 11.7944, "y": 9.4705, "w": 0.6626, "h": 0.2292, "fill": {"color": "E8E2D1"}, "line": {"type": "none"}});
  s.addText([{"text": "DRAFT", "options": {"fontSize": 9.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 0.54, "align": "left"}}], {"x": 11.8986, "y": 9.5122, "w": 0.5376, "h": 0.1875, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.roundRect, {"x": 14.1624, "y": 9.5539, "w": 2.2013, "h": 0.0625, "fill": {"color": "ECE7DC"}, "line": {"type": "none"}});
  s.addText([{"text": "—", "options": {"fontSize": 12.0, "color": "2A3D33", "fontFace": "-apple-system", "align": "left"}}], {"x": 16.5304, "y": 9.4914, "w": 1.8444, "h": 0.2292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "07 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 8 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "07 · WHAT DISTRICTS GET", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Outcomes districts can measure.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 3.2257, "w": 5.8055, "h": 3.4704, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "TEACHERS", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 1.4688, "y": 3.6528, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "5+ hours back each week.", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 1.4688, "y": 4.111, "w": 5.0999, "h": 0.9948, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Recording, assessment drafting, and re-teaching consolidate into minutes of review — not evenings at the kitchen table.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 1.4688, "y": 5.2725, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.0972, "y": 3.2257, "w": 5.8055, "h": 3.4704, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "STUDENTS", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 7.5243, "y": 3.6528, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "No lesson is ever missed.", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 7.5243, "y": 4.111, "w": 5.0999, "h": 0.9948, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Absent students, IEP students, and English learners revisit the real classroom — with captions, translation, and chaptered review.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 7.5243, "y": 5.2725, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.1527, "y": 3.2257, "w": 5.8055, "h": 3.4704, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "FAMILIES", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 13.5798, "y": 3.6528, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Visibility without friction.", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 13.5798, "y": 4.5876, "w": 5.0999, "h": 0.5182, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Parents see what was taught and where their child is stuck, without adding another meeting or email to the teacher's load.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 13.5798, "y": 5.2725, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 6.9461, "w": 5.8055, "h": 3.4705, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "ADMINISTRATORS", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 1.4688, "y": 7.3732, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Standards coverage, documented.", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 1.4688, "y": 7.8315, "w": 5.0999, "h": 0.9948, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Every lesson is auto-mapped to state standards. Pacing, coverage, and assessment data roll up across classrooms and schools.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 1.4688, "y": 8.993, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 7.0972, "y": 6.9461, "w": 5.8055, "h": 3.4705, "fill": {"color": "ECE7DC"}, "line": {"color": "D6CFBD", "width": 0.75}});
  s.addText([{"text": "PRIVACY & TRUST", "options": {"fontSize": 10.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 7.5243, "y": 7.3732, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "District-owned, FERPA-aligned.", "options": {"fontSize": 33.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 7.5243, "y": 7.8315, "w": 5.0999, "h": 0.9948, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "All recordings stay in a district tenant. Configurable retention, role-based access, and audit logs meet enterprise security reviews.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 7.5243, "y": 8.993, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 13.1527, "y": 6.9461, "w": 5.8055, "h": 3.4705, "fill": {"color": "0F1E17"}, "line": {"color": "0F1E17", "width": 0.75}});
  s.addText([{"text": "INTEGRATION", "options": {"fontSize": 10.5, "color": "F0C893", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 13.5798, "y": 7.3732, "w": 5.0999, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Works with what you already use.", "options": {"fontSize": 33.0, "color": "F4F1EA", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.04}}], {"x": 13.5798, "y": 7.8315, "w": 5.0999, "h": 0.9948, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "SSO via Clever, ClassLink, Google, Microsoft. Native export to Google Classroom, Canvas, and Schoology. No new gradebook to learn.", "options": {"fontSize": 16.5, "color": "F4F1EA", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.45}}], {"x": 13.5798, "y": 8.993, "w": 5.0999, "h": 1.0382, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "TEACHERAI · DISTRICT OVERVIEW", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 1.0417, "y": 10.5938, "w": 4.1988, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "08 / 09", "options": {"fontSize": 15.0, "color": "5C6B63", "fontFace": "Arial", "charSpacing": 1.2, "align": "left"}}], {"x": 18.2044, "y": 10.5938, "w": 0.8372, "h": 0.2812, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

// ===== Slide 9 =====
{
  const s = pptx.addSlide();
  s.background = { color: 'F4F1EA' };
  s.addText([{"text": "08 · NEXT STEP", "options": {"fontSize": 16.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 1.0417, "y": 1.0417, "w": 18.4542, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "A 90-day pilot, one school.", "options": {"fontSize": 63.0, "bold": true, "color": "0F1E17", "fontFace": "Arial", "charSpacing": -1.26, "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 1.0417, "y": 1.5833, "w": 16.0938, "h": 0.9341, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 3.1424, "w": 9.3958, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 4.7923, "w": 9.3958, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "PHASE 01 · WEEKS 1–2", "options": {"fontSize": 13.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.35, "align": "left"}}], {"x": 1.0417, "y": 3.6007, "w": 1.9583, "h": 0.4792, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Set up & onboard", "options": {"fontSize": 27.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 3.25, "y": 3.4445, "w": 2.1667, "h": 0.8291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Install room units, configure SSO and rostering, train 8–12 pilot teachers in a single 90-minute session.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.6667, "y": 3.5382, "w": 4.914, "h": 1.0041, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 6.763, "w": 9.3958, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "PHASE 02 · WEEKS 3–10", "options": {"fontSize": 13.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.35, "align": "left"}}], {"x": 1.0417, "y": 5.2507, "w": 1.9583, "h": 0.4792, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Teach & measure", "options": {"fontSize": 27.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 3.25, "y": 5.0944, "w": 2.1667, "h": 0.8291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Daily recording, weekly auto-generated assessments, and a live dashboard tracking adoption, time saved, and student engagement.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.6667, "y": 5.1882, "w": 4.914, "h": 1.3249, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 1.0417, "y": 8.4129, "w": 9.3958, "h": 0.0104, "fill": {"color": "D6CFBD"}, "line": {"type": "none"}});
  s.addText([{"text": "PHASE 03 · WEEKS 11–13", "options": {"fontSize": 13.5, "color": "1E5A3F", "fontFace": "Arial", "charSpacing": 1.35, "align": "left"}}], {"x": 1.0417, "y": 7.2214, "w": 1.9583, "h": 0.4792, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Review & expand", "options": {"fontSize": 27.0, "color": "0F1E17", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.05}}], {"x": 3.25, "y": 7.0651, "w": 2.1667, "h": 0.8291, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Outcomes report co-written with the district, with a scoped proposal to roll out across additional schools or grade bands.", "options": {"fontSize": 16.5, "color": "2A3D33", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.4}}], {"x": 5.6667, "y": 7.1589, "w": 4.914, "h": 1.0041, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 11.2708, "y": 3.1424, "w": 7.6875, "h": 8.2743, "fill": {"color": "1E5A3F"}, "line": {"type": "none"}});
  s.addText([{"text": "LET'S TALK", "options": {"fontSize": 16.5, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 2.64, "align": "left"}}], {"x": 11.7292, "y": 3.6424, "w": 6.974, "h": 0.3333, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "Pilot with us ", "options": {"fontSize": 42.0, "bold": true, "color": "F4F1EA", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.02}}, {"text": "this fall.", "options": {"fontSize": 42.0, "bold": true, "italic": true, "color": "F0C893", "fontFace": "Arial", "align": "left", "lineSpacingMultiple": 1.02}}], {"x": 11.7292, "y": 5.3133, "w": 6.974, "h": 0.647, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "We're selecting five partner districts for the 2026–27 pilot cohort. Pilot pricing is fixed; outcome data is shared openly.", "options": {"fontSize": 16.5, "color": "F4F1EA", "fontFace": "-apple-system", "align": "left", "lineSpacingMultiple": 1.5}}], {"x": 11.7292, "y": 7.3812, "w": 6.974, "h": 0.7292, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addShape(pptx.ShapeType.rect, {"x": 11.7292, "y": 9.5729, "w": 6.7708, "h": 0.0104, "fill": {"color": "F4F1EA"}, "line": {"type": "none"}});
  s.addText([{"text": "CONTACT", "options": {"fontSize": 10.5, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 11.7292, "y": 9.7917, "w": 6.974, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "pilots@teacherai.edu", "options": {"fontSize": 19.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 11.7292, "y": 9.9583, "w": 6.974, "h": 0.3646, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "APPLICATION DEADLINE", "options": {"fontSize": 10.5, "color": "F4F1EA", "fontFace": "Arial", "charSpacing": 1.26, "align": "left"}}], {"x": 11.7292, "y": 10.4271, "w": 6.974, "h": 0.2083, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
  s.addText([{"text": "June 15, 2026", "options": {"fontSize": 19.5, "color": "F4F1EA", "fontFace": "Arial", "align": "left"}}], {"x": 11.7292, "y": 10.5938, "w": 6.974, "h": 0.3646, "shape": pptx.ShapeType.rect, "margin": 2.0, "fill": {"type": "none"}, "line": {"type": "none"}, "valign": "top", "shrinkText": true});
}

pptx.writeFile({ fileName: 'TeacherAI.pptx' }).then(f => console.log('Wrote', f));